### PR TITLE
Align namespace of cache features

### LINKED ISSUE #21: stick to one namespace/prefix
With 2.3.0 there is suddenly a module named `sharded_cache`. Is it possible to stick to one prefix ie. `cache`? Thanks.

### PR DESCRIPTION
**Pull request by fogfish**
fixes #21

### CODE REVIEW

**Comment by fogfish** [comment]
@leoliu @yzh44yzh I hope you are fine with this changes. Any feedback is welcome.

**Comment by yzh44yzh** [comment]
Well, it is better )

**Comment by leoliu** [comment]
I like it too ;)

**Comment by fogfish** [comment]
hex package 2.3.1 is published

**Comment by yzh44yzh** [comment]
ok, thanks. We are going to use it.

**Pull request merged**
